name: 'Release Desktop App'

on:
  push:
    branches:
      - main # Or whatever branch you want to trigger the release from

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ 'macos-latest' ] # We are only targeting macOS for now

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: 'Install Rust'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: 'Install frontend dependencies'
        run: yarn install --frozen-lockfile

      - name: 'Build and release'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: 'dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5bTNoMlBxelRUME1xRXpvQzZHaUlrUE0zN0JQNktiek5uNDNUSmNkeGhka0FBQkFBQUFBQUFBQUFBQUlBQUFBQUxBdkFVelM5bDIvSDEzQnN2eHNXc245M3FUZllaN1RUZFpOeWVtYk40K0FTWmp3bUd3aitVcHRiUStneHBpS1BINnVPa3FRdUFSYjhCQWh6QkRpRTRUcXBoaEtRSTMzTzlPL1pOZG9VTjVBWWI1YUV3S2FPT3BPWHgzbmR5Wms3VUljN0lrTzFwUTQ9Cg=='
          # TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }} # Uncomment this if your key is password-protected
        with:
          tagName: 'v__VERSION__' # The action will automatically replace __VERSION__ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version.'
          releaseDraft: false
          prerelease: false
          args: --target aarch64-apple-darwin
